[project]
name = "hmpps-terraform-discovery"
version = "0.1.6"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hmpps-sre-python-lib",
    "tfparse==0.6.20",
]

[tool.uv.sources]
hmpps-sre-python-lib = { git = "https://github.com/ministryofjustice/hmpps-sre-python-lib", branch = "feat/HEAT-1286" }
