name: Backup Repository to SharePoint

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '10 3 * * *'

permissions: {}

jobs:
  backup:
    name: Backup to SharePoint
    runs-on: ubuntu-latest
    env:
      SP_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
      SP_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
      AZ_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Backup repository to SharePoint
        uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/sharepoint_repository_backup@662c100ddcc4f5b25e312cb7557085081aaab7fb # v1.0.10
        with:
          retention_count: 5 # optional, defaults to 5
